export type FakeDaemonRequest = {
  path: string;
  method: string;
  at: number;
  aborted: boolean;
  authorization: string | null;
  cookie: string | null;
  query?: string;
  lastEventId?: string | null;
  body?: string;
};
export function fixtureFor(node: unknown): unknown;
export function validateFixture(value: unknown, node: unknown): string[];
export const defaultFixtures: Record<string, unknown>;
export function richFixtures(): Record<string, unknown>;
export function richFiles(): Record<string, { body: string; type?: string }>;
export function inboxItemsFixture(): import("../../api/generated/types").InboxItem[];
export function noticesFixture(): import("../../api/generated/types").Notice[];
export type FakeDaemonOptions = {
  host?: string;
  port?: number;
  delayMs?: number;
  fixtures?: Record<string, unknown | ((url: URL) => unknown)>;
  token?: string | null;
  files?: Record<string, { body: string | Uint8Array | (() => string); type?: string; disposition?: string }>;
  profile?: "default" | "rich";
  fault?: { status: number; paths?: string[] } | null;
  hold?: { paths?: string[] } | null;
  streamStatus?: number;
  inboxItems?: import("../../api/generated/types").InboxItem[] | null;
  notices?: import("../../api/generated/types").Notice[] | null;
};
export function createFakeDaemon(options?: FakeDaemonOptions): {
  requests: FakeDaemonRequest[];
  sendEvent(event: string, data?: unknown): void;
  inbox: {
    items: import("../../api/generated/types").InboxItem[];
    notices: import("../../api/generated/types").Notice[];
    answers: Array<{ id: string; option?: string; note?: string; payload?: unknown }>;
  };
  setInboxItems(items: import("../../api/generated/types").InboxItem[]): void;
  setNotices(notices: import("../../api/generated/types").Notice[]): void;
  setDelay(value: number): void;
  setStreamStatus(value: number): void;
  sendConsoleBlock(block: unknown): void;
  dropConsoleClients(): void;
  setFault(rule: { status: number; paths?: string[] } | null): void;
  releaseHeld(): void;
  readonly heldCount: number;
  dropStreamClients(): void;
  setPostDelay(ms: number): void;
  readonly consoleClients: number;
  readonly streamClients: number;
  start(): Promise<string>;
  close(): Promise<void>;
};
