#!/bin/bash
# cargo の target-dir を NFS の worktree に置かず、ローカル LVM（/var/lib/celeris/build-cache/cargo/<worktree 名>）に固定する。
# - 手で: `bash scripts/dev/worktree-target-dir.sh [dir]` → <dir>（既定 cwd）の worktree 直下に .cargo/config.toml を書く（冪等）。
# - Claude Code の PreToolUse(Bash) hook から: `--hook` で stdin の JSON（cwd / tool_input.command）を読み、cargo 系の
#   コマンドのときだけ同じことをする。常に exit 0（ブロックしない）。
# 家訓: ~/.cargo/config.toml「ビルドごとに CARGO_TARGET_DIR を明示（ローカル LVM）」。CARGO_TARGET_DIR 環境変数があればそれが優先される。
set -u
BASE_DIR="${CELERIS_BUILD_CACHE:-/var/tmp/agent-platform-build}"
log(){ [ -n "${WORKTREE_TARGET_DIR_QUIET:-}" ] || echo "[worktree-target-dir] $*" >&2; }

dir="${PWD}"
if [ "${1:-}" = "--hook" ]; then
  input="$(cat 2>/dev/null || true)"
  cmd="$(printf '%s' "$input" | python3 -c 'import sys,json
try:
  d=json.load(sys.stdin); print((d.get("tool_input") or {}).get("command",""))
except Exception: print("")' 2>/dev/null)"
  case "$cmd" in
    *cargo*|*nextest*|*test-parallel*) ;;
    *) exit 0;;
  esac
  hook_cwd="$(printf '%s' "$input" | python3 -c 'import sys,json
try: print(json.load(sys.stdin).get("cwd",""))
except Exception: print("")' 2>/dev/null)"
  [ -n "$hook_cwd" ] && dir="$hook_cwd"
  WORKTREE_TARGET_DIR_QUIET=1
elif [ -n "${1:-}" ]; then
  dir="$1"
fi

root="$(git -C "$dir" rev-parse --show-toplevel 2>/dev/null)" || exit 0
[ -f "$root/Cargo.toml" ] || exit 0
# 本番リリースの build tree（/var/lib/celeris/release-build 配下）はローカルなので触らない。
case "$root" in /var/lib/celeris/*) exit 0;; esac

name="$(basename "$root")"
# 本体の checkout は「<repo 名>-main」、worktree は basename（agent-<id> など）
if [ "$(git -C "$root" rev-parse --git-dir 2>/dev/null)" = "$(git -C "$root" rev-parse --git-common-dir 2>/dev/null)" ]; then
  name="${name}-main"
fi
target="$BASE_DIR/$name"
cfg="$root/.cargo/config.toml"
want="# 生成: scripts/dev/worktree-target-dir.sh（NFS の worktree に target を書かない。~/.cargo/config.toml の家訓）
[build]
target-dir = \"$target\"
"
mkdir -p "$target" 2>/dev/null || { log "cannot create $target"; exit 0; }
if [ -f "$cfg" ] && [ "$(cat "$cfg")" = "$(printf '%s' "$want")" ]; then
  exit 0
fi
if [ -f "$cfg" ] && ! grep -q "worktree-target-dir.sh" "$cfg"; then
  log "$cfg exists and was not generated by this script; leaving it (set CARGO_TARGET_DIR yourself)"; exit 0
fi
mkdir -p "$root/.cargo" && printf '%s' "$want" > "$cfg" && log "wrote $cfg -> $target"
exit 0
