/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DaemonRouteImport } from './routes/daemon'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeInboxRouteImport } from './routes/knowledge.inbox'
import { Route as KnowledgeSkillsRouteImport } from './routes/knowledge.skills'
import { Route as OrgIndexRouteImport } from './routes/org.index'
import { Route as OrgIdRouteImport } from './routes/org.$id'
import { Route as OrgSecretaryRouteImport } from './routes/org.secretary'
import { Route as PlansNewRouteImport } from './routes/plans.new'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as TasksIdIndexRouteImport } from './routes/tasks.$id.index'
import { Route as TasksIdChangesRouteImport } from './routes/tasks.$id.changes'
import { Route as TasksIdFilesRouteImport } from './routes/tasks.$id.files'
import { Route as ProjectsIdDocsIndexRouteImport } from './routes/projects.$id.docs.index'
import { Route as ProjectsIdDocsMaintenanceRouteImport } from './routes/projects.$id.docs.maintenance'
import { Route as TasksIdRunsRunIdRouteImport } from './routes/tasks.$id.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DaemonRoute = DaemonRouteImport.update({
  id: '/daemon',
  path: '/daemon',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeInboxRoute = KnowledgeInboxRouteImport.update({
  id: '/knowledge/inbox',
  path: '/knowledge/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSkillsRoute = KnowledgeSkillsRouteImport.update({
  id: '/knowledge/skills',
  path: '/knowledge/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIdRoute = OrgIdRouteImport.update({
  id: '/org/$id',
  path: '/org/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSecretaryRoute = OrgSecretaryRouteImport.update({
  id: '/org/secretary',
  path: '/org/secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansNewRoute = PlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdIndexRoute = TasksIdIndexRouteImport.update({
  id: '/tasks/$id/',
  path: '/tasks/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdChangesRoute = TasksIdChangesRouteImport.update({
  id: '/tasks/$id/changes',
  path: '/tasks/$id/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdFilesRoute = TasksIdFilesRouteImport.update({
  id: '/tasks/$id/files',
  path: '/tasks/$id/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdDocsIndexRoute = ProjectsIdDocsIndexRouteImport.update({
  id: '/projects/$id/docs/',
  path: '/projects/$id/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdDocsMaintenanceRoute =
  ProjectsIdDocsMaintenanceRouteImport.update({
    id: '/projects/$id/docs/maintenance',
    path: '/projects/$id/docs/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const TasksIdRunsRunIdRoute = TasksIdRunsRunIdRouteImport.update({
  id: '/tasks/$id/runs/$runId',
  path: '/tasks/$id/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/approvals': typeof ApprovalsRoute
  '/artifacts': typeof ArtifactsRoute
  '/board': typeof BoardRoute
  '/clusters': typeof ClustersRoute
  '/console': typeof ConsoleRoute
  '/daemon': typeof DaemonRoute
  '/graph': typeof GraphRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/providers': typeof ProvidersRoute
  '/releases': typeof ReleasesRoute
  '/reports': typeof ReportsRoute
  '/knowledge/inbox': typeof KnowledgeInboxRoute
  '/knowledge/skills': typeof KnowledgeSkillsRoute
  '/org/$id': typeof OrgIdRoute
  '/org/secretary': typeof OrgSecretaryRoute
  '/plans/new': typeof PlansNewRoute
  '/tasks/new': typeof TasksNewRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/org/': typeof OrgIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tasks/$id/changes': typeof TasksIdChangesRoute
  '/tasks/$id/files': typeof TasksIdFilesRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
  '/projects/$id/docs/maintenance': typeof ProjectsIdDocsMaintenanceRoute
  '/tasks/$id/runs/$runId': typeof TasksIdRunsRunIdRoute
  '/projects/$id/docs/': typeof ProjectsIdDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/approvals': typeof ApprovalsRoute
  '/artifacts': typeof ArtifactsRoute
  '/board': typeof BoardRoute
  '/clusters': typeof ClustersRoute
  '/console': typeof ConsoleRoute
  '/daemon': typeof DaemonRoute
  '/graph': typeof GraphRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/providers': typeof ProvidersRoute
  '/releases': typeof ReleasesRoute
  '/reports': typeof ReportsRoute
  '/knowledge/inbox': typeof KnowledgeInboxRoute
  '/knowledge/skills': typeof KnowledgeSkillsRoute
  '/org/$id': typeof OrgIdRoute
  '/org/secretary': typeof OrgSecretaryRoute
  '/plans/new': typeof PlansNewRoute
  '/tasks/new': typeof TasksNewRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/org': typeof OrgIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/$id/changes': typeof TasksIdChangesRoute
  '/tasks/$id/files': typeof TasksIdFilesRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/tasks/$id': typeof TasksIdIndexRoute
  '/projects/$id/docs/maintenance': typeof ProjectsIdDocsMaintenanceRoute
  '/tasks/$id/runs/$runId': typeof TasksIdRunsRunIdRoute
  '/projects/$id/docs': typeof ProjectsIdDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/approvals': typeof ApprovalsRoute
  '/artifacts': typeof ArtifactsRoute
  '/board': typeof BoardRoute
  '/clusters': typeof ClustersRoute
  '/console': typeof ConsoleRoute
  '/daemon': typeof DaemonRoute
  '/graph': typeof GraphRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/providers': typeof ProvidersRoute
  '/releases': typeof ReleasesRoute
  '/reports': typeof ReportsRoute
  '/knowledge/inbox': typeof KnowledgeInboxRoute
  '/knowledge/skills': typeof KnowledgeSkillsRoute
  '/org/$id': typeof OrgIdRoute
  '/org/secretary': typeof OrgSecretaryRoute
  '/plans/new': typeof PlansNewRoute
  '/tasks/new': typeof TasksNewRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/org/': typeof OrgIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tasks/$id/changes': typeof TasksIdChangesRoute
  '/tasks/$id/files': typeof TasksIdFilesRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
  '/projects/$id/docs/maintenance': typeof ProjectsIdDocsMaintenanceRoute
  '/tasks/$id/runs/$runId': typeof TasksIdRunsRunIdRoute
  '/projects/$id/docs/': typeof ProjectsIdDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/approvals'
    | '/artifacts'
    | '/board'
    | '/clusters'
    | '/console'
    | '/daemon'
    | '/graph'
    | '/help'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/providers'
    | '/releases'
    | '/reports'
    | '/knowledge/inbox'
    | '/knowledge/skills'
    | '/org/$id'
    | '/org/secretary'
    | '/plans/new'
    | '/tasks/new'
    | '/knowledge/'
    | '/org/'
    | '/projects/'
    | '/tasks/'
    | '/tasks/$id/changes'
    | '/tasks/$id/files'
    | '/projects/$id/'
    | '/tasks/$id/'
    | '/projects/$id/docs/maintenance'
    | '/tasks/$id/runs/$runId'
    | '/projects/$id/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/approvals'
    | '/artifacts'
    | '/board'
    | '/clusters'
    | '/console'
    | '/daemon'
    | '/graph'
    | '/help'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/providers'
    | '/releases'
    | '/reports'
    | '/knowledge/inbox'
    | '/knowledge/skills'
    | '/org/$id'
    | '/org/secretary'
    | '/plans/new'
    | '/tasks/new'
    | '/knowledge'
    | '/org'
    | '/projects'
    | '/tasks'
    | '/tasks/$id/changes'
    | '/tasks/$id/files'
    | '/projects/$id'
    | '/tasks/$id'
    | '/projects/$id/docs/maintenance'
    | '/tasks/$id/runs/$runId'
    | '/projects/$id/docs'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/approvals'
    | '/artifacts'
    | '/board'
    | '/clusters'
    | '/console'
    | '/daemon'
    | '/graph'
    | '/help'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/providers'
    | '/releases'
    | '/reports'
    | '/knowledge/inbox'
    | '/knowledge/skills'
    | '/org/$id'
    | '/org/secretary'
    | '/plans/new'
    | '/tasks/new'
    | '/knowledge/'
    | '/org/'
    | '/projects/'
    | '/tasks/'
    | '/tasks/$id/changes'
    | '/tasks/$id/files'
    | '/projects/$id/'
    | '/tasks/$id/'
    | '/projects/$id/docs/maintenance'
    | '/tasks/$id/runs/$runId'
    | '/projects/$id/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  ArtifactsRoute: typeof ArtifactsRoute
  BoardRoute: typeof BoardRoute
  ClustersRoute: typeof ClustersRoute
  ConsoleRoute: typeof ConsoleRoute
  DaemonRoute: typeof DaemonRoute
  GraphRoute: typeof GraphRoute
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProvidersRoute: typeof ProvidersRoute
  ReleasesRoute: typeof ReleasesRoute
  ReportsRoute: typeof ReportsRoute
  KnowledgeInboxRoute: typeof KnowledgeInboxRoute
  KnowledgeSkillsRoute: typeof KnowledgeSkillsRoute
  OrgIdRoute: typeof OrgIdRoute
  OrgSecretaryRoute: typeof OrgSecretaryRoute
  PlansNewRoute: typeof PlansNewRoute
  TasksNewRoute: typeof TasksNewRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  OrgIndexRoute: typeof OrgIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TasksIdChangesRoute: typeof TasksIdChangesRoute
  TasksIdFilesRoute: typeof TasksIdFilesRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  TasksIdIndexRoute: typeof TasksIdIndexRoute
  ProjectsIdDocsMaintenanceRoute: typeof ProjectsIdDocsMaintenanceRoute
  TasksIdRunsRunIdRoute: typeof TasksIdRunsRunIdRoute
  ProjectsIdDocsIndexRoute: typeof ProjectsIdDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daemon': {
      id: '/daemon'
      path: '/daemon'
      fullPath: '/daemon'
      preLoaderRoute: typeof DaemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/inbox': {
      id: '/knowledge/inbox'
      path: '/knowledge/inbox'
      fullPath: '/knowledge/inbox'
      preLoaderRoute: typeof KnowledgeInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/skills': {
      id: '/knowledge/skills'
      path: '/knowledge/skills'
      fullPath: '/knowledge/skills'
      preLoaderRoute: typeof KnowledgeSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/org'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$id': {
      id: '/org/$id'
      path: '/org/$id'
      fullPath: '/org/$id'
      preLoaderRoute: typeof OrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/secretary': {
      id: '/org/secretary'
      path: '/org/secretary'
      fullPath: '/org/secretary'
      preLoaderRoute: typeof OrgSecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/new': {
      id: '/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof PlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id/': {
      id: '/tasks/$id/'
      path: '/tasks/$id'
      fullPath: '/tasks/$id/'
      preLoaderRoute: typeof TasksIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id/changes': {
      id: '/tasks/$id/changes'
      path: '/tasks/$id/changes'
      fullPath: '/tasks/$id/changes'
      preLoaderRoute: typeof TasksIdChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id/files': {
      id: '/tasks/$id/files'
      path: '/tasks/$id/files'
      fullPath: '/tasks/$id/files'
      preLoaderRoute: typeof TasksIdFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/docs/': {
      id: '/projects/$id/docs/'
      path: '/projects/$id/docs'
      fullPath: '/projects/$id/docs/'
      preLoaderRoute: typeof ProjectsIdDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/docs/maintenance': {
      id: '/projects/$id/docs/maintenance'
      path: '/projects/$id/docs/maintenance'
      fullPath: '/projects/$id/docs/maintenance'
      preLoaderRoute: typeof ProjectsIdDocsMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id/runs/$runId': {
      id: '/tasks/$id/runs/$runId'
      path: '/tasks/$id/runs/$runId'
      fullPath: '/tasks/$id/runs/$runId'
      preLoaderRoute: typeof TasksIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ApprovalsRoute: ApprovalsRoute,
  ArtifactsRoute: ArtifactsRoute,
  BoardRoute: BoardRoute,
  ClustersRoute: ClustersRoute,
  ConsoleRoute: ConsoleRoute,
  DaemonRoute: DaemonRoute,
  GraphRoute: GraphRoute,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProvidersRoute: ProvidersRoute,
  ReleasesRoute: ReleasesRoute,
  ReportsRoute: ReportsRoute,
  KnowledgeInboxRoute: KnowledgeInboxRoute,
  KnowledgeSkillsRoute: KnowledgeSkillsRoute,
  OrgIdRoute: OrgIdRoute,
  OrgSecretaryRoute: OrgSecretaryRoute,
  PlansNewRoute: PlansNewRoute,
  TasksNewRoute: TasksNewRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  OrgIndexRoute: OrgIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TasksIdChangesRoute: TasksIdChangesRoute,
  TasksIdFilesRoute: TasksIdFilesRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  TasksIdIndexRoute: TasksIdIndexRoute,
  ProjectsIdDocsMaintenanceRoute: ProjectsIdDocsMaintenanceRoute,
  TasksIdRunsRunIdRoute: TasksIdRunsRunIdRoute,
  ProjectsIdDocsIndexRoute: ProjectsIdDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
